### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by SergeySypalo** [tinohager/Nager.AmazonProductAdvertising#1]
Hello,

Thx for awesome package!

I wanted to ask about how to get results from second page, i.e. looking for pagination and some docs how to use it

I'm going to use havily your package, but because I'm not true developer so I can help with writing some docs if needed or add example project (currently developing a website using ASP.NET 5 and will switch to ASP.NET Core once it will be released)

Br, Sergey

**Comment by tinohager** [comment]
Hello

You must add the Namespace 'using Nager.AmazonProductAdvertising.Extension;' and then you can change the page with 'ItemPage' maxium 5 pages available.

`
var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.DE);
var searchQuery = wrapper.ItemSearchOperation("canon eos", AmazonSearchIndex.Electronics);
searchQuery = searchQuery.ItemPage(2);
var xml = wrapper.Request(searchQuery);
var result = XmlHelper.ParseXml<ItemSearchResponse>(xml);
`

**Comment by SergeySypalo** [comment]
Thx a lot for the code example, somehow I missed ItemPage method, tried searchQuery.Skip(2) instead

**Comment by umitatestr** [comment]
Hi tinohager,
I downloaded Nager.AmazonProductAdvertising 1.0.1 and Nager.AmazonProductAdvertising 1.0.22. I'm reviewing and doing some tests. But I have not found how to use the ItemPage property for paging.

SearchQuery = searchQuery.ItemPage (2);

When I try to use it like this in the example above, the ItemPage property is not found in ItemSearchOperation.

Can you help with this?

Thank you.

Ümit

**Comment by tinohager** [comment]
Try this

    var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.DE);
    var searchOperation = wrapper.ItemSearchOperation("canon eos", AmazonSearchIndex.Electronics);
    searchOperation.Sort(AmazonSearchSort.Price, AmazonSearchSortOrder.Descending);
    searchOperation.Skip(1);
    var webResponse = wrapper.Request(searchOperation);

**Comment by umitatestr** [comment]
![untitled](https://cloud.githubusercontent.com/assets/25739073/22992870/a837fd86-f3c9-11e6-90b4-ba20ecaa88b3.jpg)

Unfortunately, it still does not come.

**Comment by tinohager** [comment]
Use Skip method

Am 15.02.2017 um 20:57 schrieb umitatestr <notifications@github.com<mailto:notifications@github.com>>:


[untitled]<https://cloud.githubusercontent.com/assets/25739073/22992870/a837fd86-f3c9-11e6-90b4-ba20ecaa88b3.jpg>

Unfortunately, it still does not come.

**Comment by umitatestr** [comment]
I do not understand what you mean?

**Comment by tinohager** [comment]
Use Skip() method - ItemPage is obsolete

**Comment by umitatestr** [comment]
If you are looking for a good product, the result is more than 5 pages. We can enter a value between 1 and 5 in the Skip () method. It gives a warning when it sends page number 6.

**Comment by tinohager** [comment]
http://docs.aws.amazon.com/AWSECommerceService/latest/DG/ItemSearch.html

Returns a specific page of items from the available search results. Up to ten items are returned per page.

If you do not include ItemPage in your request, the first page is returned. The total number of pages found is returned in the TotalPages response element.

If Condition is set to All, ItemSearch returns additional offers for those items, one offer per condition type.

Valid values: 1 to 10 (1 to 5 when search index is All)
