### ISSUE TITLE
Not Finding an Item but your demo from readme.md finds it :(

### ISSUE THREAD

**Issue by pkellner** [tinohager/Nager.AmazonProductAdvertising#100]
I'm sending the c#:

`client.GetItemsAsync("0596517742")`

Which is Crockford's JavaScript the Good Parts
https://www.amazon.com/JavaScript-Good-Parts-Douglas-Crockford/dp/0596517742

and it returns an error. When I look for Crockford's new book with the id 1949815005 it finds that.

I'm sure I'm missing something really simple but am still confused :(.

https://www.amazon.com/How-JavaScript-Works-Douglas-Crockford/dp/1949815005/ref=sr_1_1?keywords=crockford&qid=1569978234&s=books&sr=1-1

**Comment by tinohager** [comment]
you can publish more information about the error?
