### ISSUE TITLE
I missed 2 items on PAAPI5

### ISSUE THREAD

**Issue by WagnerW** [tinohager/Nager.AmazonProductAdvertising#103]
Hi nager, I now know of the changes the end date is October 31st, else I didn't find "ItemInfo.ManufactureInfo" on Paapi, and "EditorialReviews" like Amazon can an API be released without the product description

**Comment by tinohager** [comment]
Please ask your question direct to amazon. [pa-api-40-to-50-mapping](https://webservices.amazon.com/paapi5/documentation/migration-guide/pa-api-40-to-50-mapping.html)

**Comment by WagnerW** [comment]
![PAPPI5](https://user-images.githubusercontent.com/10757756/66867159-138f1d80-ef71-11e9-9c53-106c04a17255.JPG)

**Comment by WagnerW** [comment]
Model PAAPI 4 and ItemInfo.ManufactureInfo PAAPI5 I can not find

**Comment by WagnerW** [comment]
Thanks

**Comment by tinohager** [comment]
What exactly is your question now?

**Comment by WagnerW** [comment]
I did not understand, did not find the key "ItemInfo.ManufactureInfo" in your code

**Comment by tinohager** [comment]
This is a valid resource, you can set your own ressources for a request.

https://github.com/tinohager/Nager.AmazonProductAdvertising/blob/master/src/Nager.AmazonProductAdvertising/AmazonResourceValidator.cs#L41

**Comment by WagnerW** [comment]
Sorry now got it, thanks

**Comment by rjnu79** [comment]
In https://github.com/tinohager/Nager.AmazonProductAdvertising/blob/master/src/Nager.AmazonProductAdvertising/AmazonResourceValidator.cs#L41 it is "ItemInfo.ManufacturerInfo"

However, according to https://webservices.amazon.com/paapi5/documentation/item-info.html it should be **"ItemInfo.ManufactureInfo"** (no 'r')

Is there any way to get "ItemInfo.ManufactureInfo" in the current release of Nager.AmazonProductAdvertising?

**Comment by tinohager** [comment]
The Amazon documentation has a failure.

I have publish a new version

https://webservices.amazon.com/paapi5/documentation/search-items.html
![image](https://user-images.githubusercontent.com/8215186/67165260-5a22b480-f383-11e9-8c12-81e2027c77e1.png)

**Comment by WagnerW** [comment]
How can I make the filter call by "SearchIndex" in PAAPI 4 you selected the filter before

{
   **"SearchIndex": "Electronics",**
   "Keywords": "DSLR Camera",
   "Resources": ["Images.Primary.Medium", "ItemInfo.Title", "Offers.Listings.Price"]
}
