### ISSUE TITLE
it's slow.

### ISSUE THREAD

**Issue by aiser86** [tinohager/Nager.AmazonProductAdvertising#104]
Hi everybody, i'm not a good programmer, but since last version of Nager library, mywebsite works fine.

Now I've  installed the last release and I re write my code, but, i've a huge problem.

When i call  this method  `var result = await client.GetItemsAsync(asin); ` I received a response like this:

"WaitingForActivation" with related id.

How can I resolve?
Thanks.

**Comment by tinohager** [comment]
i think you are use the async await wrong...

**Comment by aiser86** [comment]
you are right, i resolve the issue right now!
I'm sorry.
Thanks

Il giorno mer 23 ott 2019 alle ore 21:20 Tino Hager <
notifications@github.com> ha scritto:
