### ISSUE TITLE
Sign error starts to prompt today

### ISSUE THREAD

**Issue by molidestroyer** [tinohager/Nager.AmazonProductAdvertising#105]
Hi, 

Thanks for the amazing library! From today it starts to throw an error when I try to get items by asin.

System.Exception: 'The request has not been correctly signed. If you are using an AWS SDK, requests are signed for you automatically; otherwise, go to https://webservices.amazon.es/paapi5/documentation/sending-request.html#signing.'

I'm running using latest version 2.0.4, it was working fine but today i started to get this issue

**Comment by tinohager** [comment]
I checked with me, I'm not getting any mistakes.

**Comment by molidestroyer** [comment]
ok, i'll check if I changed something else. Thanks anyway @tinohager

**Comment by molidestroyer** [comment]
method i'm using it's GetItemsAsync([array of ASIN]) aiming to ES if it helps, still getting it.

**Comment by molidestroyer** [comment]
Mistery solved! My clock didn't update the summer time, this was causing the error!

This piece of code outside my local helps me a bit to find out: https://dotnetfiddle.net/nBwRTn
