### ISSUE TITLE
PAAPI4 working

### ISSUE THREAD

**Issue by WagnerW** [tinohager/Nager.AmazonProductAdvertising#107]
Hi someone was disconnected from PAAPI4? here in Brazil is still working

**Comment by tinohager** [comment]
On my site is still working too

**Comment by WagnerW** [comment]
Just think that Amazon is making us give up the API, because here in my tests V.5 is returning direct "TooManyRequest" error 429 and when accessing your site Nager.Shop is also with the same problem.

**Comment by WagnerW** [comment]
Hi TinoHager, is the Nager.Shop website V.4 or V.5? Realized that you are returning error 429 with a few clicks, I don't realize this as often in V.4

[https://1drv.ms/u/s!AsxsQEKkH-KjjrgQAC7QNpUOjCbDbQ](url)
