### ISSUE TITLE
Program stack during http request

### ISSUE THREAD

**Issue by tojan97** [tinohager/Nager.AmazonProductAdvertising#113]
(Sorry i open and close another issue, first time on github sorry), when i try to search an item the program stack during http request, i try  api to be sure on scratchpad and there they work;
Program stack there

using (var responseMessage = await this._httpClient.SendAsync(request, this._amazonEndpointConfig.Region, serviceName, this._credentials))

What could be the problem?

**Comment by tinohager** [comment]
sorry i not understand your question

**Comment by tojan97** [comment]
I tried your code,the first example : Item Search (simple), when i start the program it  does nothing, no errors, but the program  is stuck on one line, the line is that one

using (var responseMessage = await this._httpClient.SendAsync(request, this._amazonEndpointConfig.Region, serviceName, this._credentials))

and therefore the problem is when the programa try tu send the item request to amazon servers

(sorry for my english)

**Comment by tinohager** [comment]
winform application?

**Comment by tojan97** [comment]
yes

**Comment by tinohager** [comment]
The library is not working with winform. configureawait is not implemented
https://devblogs.microsoft.com/dotnet/configureawait-faq/

**Comment by tojan97** [comment]
ah ok thanks, there are no alternatives?the only way is to use this on console application?

**Comment by tinohager** [comment]
or create a fork and add the configureawait for your issue

**Comment by tojan97** [comment]
ok thanks for the support
