### ISSUE TITLE
BrowseNodeLookupResponse

### ISSUE THREAD

**Issue by hackinc2000** [tinohager/Nager.AmazonProductAdvertising#14]
I can't figure why 

**BrowseNodeLookupResponse its not returning any child nodes of type BrowseNode or BrowswNodes  when they exist in the response

**Comment by hackinc2000** [comment]
What I'm trying to do:

            var nodeLook = wrapper.BrowseNodeLookupOperation(165797011,AmazonResponseGroup.TopSellers);
            var nodeResp = wrapper.Request(nodeLook);

            var nodeResult = XmlHelper.ParseXml<BrowseNodeLookupResponse>(nodeResp.Content);

**Comment by tinohager** [comment]
One Problem is the id is not valid, check documentation http://docs.aws.amazon.com/AWSECommerceService/latest/DG/localevalues.html
```
nodeResult.BrowseNodes.Request.Errors[0].Message
"165797011 is not a valid value for BrowseNodeId. Please change this value and retry your request."
```

The second problem i must change the xml parse logic for the new elements. I add it in the next version.

**Comment by tinohager** [comment]
I have publish the new Version 1.0.13 with the bugfix
