### ISSUE TITLE
This doesn't work for me

### ISSUE THREAD

**Issue by mrsmirf** [tinohager/Nager.AmazonProductAdvertising#15]
I get result = null when I debug to see it.
Also the metadata file has ` AmazonWrapper(AmazonAuthentication authentication, AmazonEndpoint endpoint, string associateTag = "nagerat-21");`

Code:

`var authentication = new AmazonAuthentication();
            authentication.AccessKey = "A...A";
            authentication.SecretKey = "Y...Y";
            var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.DE, "s...0");
            //var result = wrapper.Search("htc", AmazonSearchIndex.Electronics, AmazonResponseGroup.Large);
            var result = wrapper.Lookup("B01H5PQGD2");
            Console.WriteLine(result);
            Console.ReadLine();`

**Comment by tinohager** [comment]
Amazon api result have a error Items->Request->Errors
"B01H5PQGD2 is not a valid value for ItemId. Please change this value and retry your request."

the metadata is correct for testing is my tag deposited

**Comment by tinohager** [comment]
maybe you must change the endpoint to AmazonEndpoint.US
