### ISSUE TITLE
Ancestors missing from BrowseNode

### ISSUE THREAD

**Issue by cmenser** [tinohager/Nager.AmazonProductAdvertising#16]
BrowseNode should have an Ancestors attribute in it as such:

        public Ancestors Ancestors { get; set; }

I'm currently using having to use custom classes and my own call to XmlHelper.ParseXml in order to get the Ancestors when making a BrowseNodeLookupOperation request.

Would love to see this fix in the nuget. If you would prefer I could pull the source and make a pull request.

**Comment by tinohager** [comment]
fixed in new version 1.0.15

**Comment by cmenser** [comment]
Thanks. However it appears your 1.0.15 nuget has the 1.0.14 assembly in it.

Also... You have a class of Ancenstors that you could use instead of BrowseNode[] (However I do believe through testing that both solutions work)

**Comment by tinohager** [comment]
sorry i have publish 1.0.16 now with the current assembly
