### ISSUE TITLE
Please add attribute "quantity" next version.

### ISSUE THREAD

**Issue by golfreshy** [tinohager/Nager.AmazonProductAdvertising#17]
Example I lookup B003XDKPJM. 
( https://www.amazon.com/Happy-Sales-B003XDKPJM-Cast-Bamboo/dp/B003XDKPJM?SubscriptionId=AKIAIXL7S5PNVYVXBHS ) 

I cant see this word "Only 18 left in stock.". Please add quantity as soon as possible. Thank you very much.

**Comment by tinohager** [comment]
Is this information in the xml data available?

**Comment by tinohager** [comment]
I have check the XML response but no stock info is available

**Comment by tinohager** [comment]
[response-xml.txt](https://github.com/tinohager/Nager.AmazonProductAdvertising/files/493635/response-xml.txt)
