### ISSUE TITLE
NuGet Install Error with Xamarin Studio

### ISSUE THREAD

**Issue by dmasur** [tinohager/Nager.AmazonProductAdvertising#18]
Hi,

i tried to add this package to my Xamarin Studio App, but i got this error message: 

```
Adding Nager.AmazonProductAdvertising...
Adding 'Nager.AmazonProductAdvertising 1.0.16' to BGCLib.
Could not install package 'Nager.AmazonProductAdvertising 1.0.16'. You are trying to install this package into a project that targets 'portable-net45+sl50+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarintvos10+xamarinwatchos10+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

Is this a bigger problem to support Xamarin, or just a matter of config?

Greetings,
Dominik

**Comment by tinohager** [comment]
I think is no problem i check your requirement the next days....

**Comment by tinohager** [comment]
Hi Dominik

I think you need a portable class library Project. You can download the source code here. I think is not only a config change in the project.
