### ISSUE TITLE
Multiple Response Groups

### ISSUE THREAD

**Issue by cecilphillip** [tinohager/Nager.AmazonProductAdvertising#2]
Is there a way to supply multiple ResponseGroups, similar to how you can in the Amazon [scratchpad](http://webservices.amazon.com/scratchpad/index.html) ?

Maybe by marking the AmazonResponseGroup with the FlagsAttribute

**Comment by tinohager** [comment]
i change this in the next version

**Comment by cecilphillip** [comment]
If you accept pull requests I can try to put something together

**Comment by tinohager** [comment]
Yes i accept pull requests 👍
