### ISSUE TITLE
Always returning null

### ISSUE THREAD

**Issue by tonyyyrocks39** [tinohager/Nager.AmazonProductAdvertising#20]
var authentication = new AmazonAuthentication();
            authentication.AccessKey = "*********";
            authentication.SecretKey = "***********";

            var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.IN);
            var result = wrapper.Lookup("B00KBBRSKI");

**Comment by egaia** [comment]
Please try using this on http://webservices.amazon.co.uk/scratchpad/index.html#

See if you get any smarter

**Comment by tonyyyrocks39** [comment]
I am closing this....I found the issue and fixed it....
I must say this is an excellent wrapper.

**Comment by anilshivamber** [comment]
hi ghost getting the same error how did you fix?
