### ISSUE TITLE
AmazonItemResponse & BrowseNodes

### ISSUE THREAD

**Issue by ltung** [tinohager/Nager.AmazonProductAdvertising#21]
Just wonder if you plan to include BrowseNodes in AmazonItemResponse. In the XML & Amazon API, they do have a BrowseNodes in the Response (so as to categorize the item). However, in AmazonResult.cs

public class Item {
...
}

It only includes up to SimilarProducts.

**Comment by ltung** [comment]
Ok. I did some simple test. Just by adding these 2 lines into Item class in AmazonResult.cs after "public SimilarProductsSimilarProduct[] SimilarProducts { get; set; }" should work:

        [XmlArrayItem("BrowseNode", IsNullable = false)]
        public BrowseNode[] BrowseNodes { get; set; }

**Comment by tinohager** [comment]
Hi Itung i check this the next days, thanks

**Comment by tinohager** [comment]
bugix is available in the new Version 1.0.18
