### ISSUE TITLE
List all children of Node

### ISSUE THREAD

**Issue by dimentorium** [tinohager/Nager.AmazonProductAdvertising#23]
Hi Tino, 
is it somehow possible with the API to list all items inside a browse node? Comparable to this one

http://webservices.amazon.com/onca/xml?
Service=AWSECommerceService&
AWSAccessKeyId=[AWS Access Key ID]&
AssociateTag=[Associate Tag]&
Operation=ItemSearch&
Keywords=tall&
SearchIndex=Apparel&
BrowseNode=123456
&Timestamp=[YYYY-MM-DDThh:mm:ssZ]
&Signature=[Request Signature]

http://docs.aws.amazon.com/AWSECommerceService/latest/DG/FindingItemsUsingBrowseNodes.html

Just checked in the code, but in the Search Operation there is no Browse node argument.

Cheers Phil

**Comment by tinohager** [comment]
You can use the OperationBase class.

            var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.DE);
            var customOperation = new AmazonOperationBase();
            customOperation.ParameterDictionary.Add("Operation", "ItemSearch");
            customOperation.ParameterDictionary.Add("Keywords", "tall");
            customOperation.ParameterDictionary.Add("SearchIndex", "Apparel");
            customOperation.ParameterDictionary.Add("BrowseNode", "78193031");
            customOperation.ParameterDictionary.Add("AssociateTag", "nagerat-21");

            var webResponse = wrapper.Request(customOperation);

            var result = XmlHelper.ParseXml<ItemSearchResponse>(webResponse.Content);

            foreach (var item in result.Items.Item)
            {
                Console.WriteLine(item.ItemAttributes.Title);
            }

            Console.WriteLine("found {0} items", result.Items.Item.Length);

            Console.WriteLine("------------------------------------------");

**Comment by dimentorium** [comment]
Hi Tino,

awesome, thanks a lot!!
