### ISSUE TITLE
Paging results

### ISSUE THREAD

**Issue by chedgzoy** [tinohager/Nager.AmazonProductAdvertising#24]
Its not a issue as such but really struggling to see how to get a 2nd page of results 
so items 1 - 10 then items 11 - 20 
or to get the first 100 items

Sorry if this is the wrong place to ask

**Comment by tinohager** [comment]
Hi a quick example of paging

	var authentication = new AmazonAuthentication();
	authentication.AccessKey = "accesskey";
	authentication.SecretKey = "secretkey";

	var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.DE, "nagerat-21");
	var searchOperation = wrapper.ItemSearchOperation("canon eos", AmazonSearchIndex.Electronics);
	searchOperation.Sort(AmazonSearchSort.Price, AmazonSearchSortOrder.Descending);
	searchOperation.Skip(2);
	var xmlResponse = wrapper.Request(searchOperation);

	var result = XmlHelper.ParseXml<ItemSearchResponse>(xmlResponse.Content);

**Comment by brkzkn** [comment]
Hi,

I have 68 pages results. When I try to .Skip(11), I got error message. The value should be between 1-10. How can I get results more than 10 pages? 

Thank you,

**Comment by tinohager** [comment]
Max pages on a search is 10
https://docs.aws.amazon.com/AWSECommerceService/latest/DG/PagingandSortingThroughResults.html#MaximumNumberofPages
