### ISSUE TITLE
Examples from readme

### ISSUE THREAD

**Issue by youlead514** [tinohager/Nager.AmazonProductAdvertising#25]
FYI, not sure if its based on my location but the examples didn't work till I changed
AmazonEndpoint.DE to AmazonEndpoint.US, It tripped me up for a second till I figured it out.
Thanks for putting your time into this.  Saved me a ton of work.

**Comment by tinohager** [comment]
Hi, thanks for your feedback i optimize the exampels. I'm glad that my project helped you.

**Comment by tinohager** [comment]
i have update the documentation, i hope now is better

**Comment by youlead514** [comment]
Great, thanks
