### ISSUE TITLE
AmazonWrapper.cs error

### ISSUE THREAD

**Issue by DukeNuken** [tinohager/Nager.AmazonProductAdvertising#3]
hello.

I see in the file some strange code 

` this.XmlReceived?.Invoke(xml);`

What is that? Symbol "?" that code doesnt work

**Comment by tinohager** [comment]
Is new C# 6.0 Syntax

https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#null-conditional-operators

**Comment by DukeNuken** [comment]
I see. I just run it in vs 2013 and saw that error. Closed
