### ISSUE TITLE
product limits

### ISSUE THREAD

**Issue by chedgzoy** [tinohager/Nager.AmazonProductAdvertising#30]
Fantastic project, really has helped me speed up my project.
Can I ask is there anyway of getting more than 50 products. 
10 per page (5 pages) 
Could really do with 100 products to match others like eBay etc. 

Sorry Its not really an issue with this project and more of a question but was struggling to find a way of asking.

**Comment by tinohager** [comment]
Hi

You can search with different sorting for example:

    searchOperation.Sort(AmazonSearchSort.Price, AmazonSearchSortOrder.Descending);
    searchOperation.Sort(AmazonSearchSort.Salesrank, AmazonSearchSortOrder.Descending);

**Comment by chedgzoy** [comment]
Thank you for the response. I guess that could give me 100 results by doing 2 searches. I would need to remove duplicates but thats ok. 
I would assume the limit is set by amazon and not the nager project.

**Comment by tinohager** [comment]
you're welcome, more infos about the limits of amazon you can find on this page

http://docs.aws.amazon.com/AWSECommerceService/latest/DG/PagingandSortingThroughResults.html

**Maximum Number Of Returned Pages**
The Product Advertising API has the following page result limits:

| Operation | Parameter Name | Maximum Page Number |
|----------|-------------:|------:|
| ItemLookup |  VariationPage | 150 |
| ItemSearch | ItemPage | 10 |
