### ISSUE TITLE
Net Core compatibility

### ISSUE THREAD

**Issue by TechWatching** [tinohager/Nager.AmazonProductAdvertising#31]
Would it be possible to make it compatible with .net core / .net standard ? Seems a really interesting nuget package to me but I can't use it in my .Net Core projects as it is not compatible.

**Comment by TechWatching** [comment]
After thinking, in fact considering targeting the latest version of  .net standard coffee possible ould be the right thing as it will make it available everywhere including .Net core

**Comment by TechWatching** [comment]
Coffee => if 
Ould => could

**Comment by tinohager** [comment]
I have check my project with the analyer https://github.com/Microsoft/dotnet-apiport
Its dependent of the .net standard version i have 100% compatibility with version 2.0 the version 1.6 missing XML Attributes and webclient...

The release date for 2.0 is planned for Spring 2017

**Comment by TechWatching** [comment]
Okay. Thanks for having checked. Let's wait the release then. Nice lib by the way.

**Comment by tekguy** [comment]
Thanks @tinohager and @TechWatching been looking for this, my work around for now is to use a .NET 4.5 project and use a service bus to add products to my database, then my .NET core project will read the products from the database. Just an example of some creative things you can try for now till it's converted.

**Comment by TechWatching** [comment]
Why not indeed. As for me I chose to use an asp.net core project which targets .net framework. Still an asp.net core app, just not cross platform

**Comment by tinohager** [comment]
Update
.NET Standard 2.0 - Release Date Q3 2017

**Comment by ElanHasson** [comment]
As we get closer to the .Net standard 2.0 release date, [milestone is at 99%](https://github.com/dotnet/corefx/milestone/4), do you have a preview branch?

**Comment by tinohager** [comment]
No at the moment i have no preview branch. Do you urgently need a new Version?

**Comment by ElanHasson** [comment]
Hi Tino,

I am happy to work on a port, as it's something I'll need very soon.

**Comment by ElanHasson** [comment]
Instead of branch, we can use a vNext folder in the root to facilitate the port.

We would probably want to produce nugets that target all supported runtimes.

Thoughts?

**Comment by ElanHasson** [comment]
I went ahead and did the port in #49

**Comment by tinohager** [comment]
Hi a new nuget package is available. Thanks Elan for a good preview!
