### ISSUE TITLE
Null Error Recieved & Null Result previously working code.

### ISSUE THREAD

**Issue by daggertom** [tinohager/Nager.AmazonProductAdvertising#32]
When running this code the ErrorReceived event fires with AmazonErrorResponse obj being null:

`			AmazonAuthentication auth = new AmazonAuthentication();
			auth.AccessKey = "################";
			auth.SecretKey = "#################";
			
			AmazonWrapper wrapper = new AmazonWrapper(auth, AmazonEndpoint.UK,"###########");
			List<string> barcodesToLookup = new List<string>();
			
			foreach(Product p in products)
			{
				barcodesToLookup.Add(p.barcode);
			}
			wrapper.XmlReceived += wrapper_XmlReceived;
			wrapper.ErrorReceived += wrapper_ErrorReceived;
			var result = wrapper.Lookup(barcodesToLookup.ToArray());`

I have subscribed to the event which fires.. however the recieved error response is null producing the null error dialog

```
void wrapper_ErrorReceived(AmazonErrorResponse obj)
		{
			if (obj == null) {MessageBox.Show("Null obj???");return;} // <--- This fires
			MessageBox.Show(obj.Error.ToString());
			MessageBox.Show(obj.Error.Code + " " + obj.Error.Message);
		}
```

The XmlRecieved event does not fire.

What is odd is, this request was previously working just fine, on a different machine - So I know this code can work - I'm having a hard time debugging without any error information, any help appreciated!

**Comment by tinohager** [comment]
Can you please add one of your Barcodes?
