### ISSUE TITLE
Separating Model classes into separate project

### ISSUE THREAD

**Issue by jordanwallwork** [tinohager/Nager.AmazonProductAdvertising#33]
I'm considering using this in a project of mine, and I want to save the search info. Rather than recreating the models in my domain project I'd prefer to reference the model classes directly - however I don't want the dependency to the full Nager.AmazonProductAdvertising. This would be trivial to do if I moved Nager.AmazonProductAdvertising.Models into it's own project however.

If I was to fork the project and make this change, would it be something that you would be willing to merge in if I submitted a PR? I don't want to miss out on future updates, so if it's not something you'd be interested in then I shan't bother and I'll just copy the models instead

**Comment by tinohager** [comment]
The big part of the project are the models i think is not useful to split in two parts. I think a simple solution is use a own model on your site and map this with automapper or manual.

**Comment by jordanwallwork** [comment]
Ok no worries
