### ISSUE TITLE
Ability to suport remote CartView etc

### ISSUE THREAD

**Issue by frankmat** [tinohager/Nager.AmazonProductAdvertising#34]
Hi I am just wondering if there is any plan to include in the wrapper support for having an external cart and being able to read from it?

**Comment by tinohager** [comment]
At the moment i have no plan. But the project is open to add this feature.

**Comment by frankmat** [comment]
Oh ok great.  Everything worked well but I can only add carts obviously via amazon... where I wanted to do it externally and within my website.  Because the CartView etc isn't within the wrapper I was struggling in getting that functionality working  :(
