### ISSUE TITLE
Timestamp is invalid. Reason: Must be in ISO8601 format.

### ISSUE THREAD

**Issue by landlogicit** [tinohager/Nager.AmazonProductAdvertising#36]
Hi,
please check this error:
Value 2017-03-09T23.15.24Z for parameter Timestamp is invalid. Reason: Must be in ISO8601 format.

**Comment by tinohager** [comment]
Hi

Thanks for the pull i have check the Problem i found probems on the following cultures.
I think this change is ony i need.

    request.Add("Timestamp", DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", CultureInfo.InvariantCulture));

ar-SA
bn-BD
bn-IN
da-GL
en-DK
en-FI
fa-IR
fi-FI
id-ID
jv-Java-ID
jv-Latn-ID
ku-Arab-IR
lrc-IR
mzn-IR
nb-NO
nb-SJ
oc-FR
pa-Arab-PK
prs-AF
ps-AF
si-LK
sr-Cyrl-XK
sr-Latn-BA
sr-Latn-ME
sr-Latn-RS
sr-Latn-XK
th-TH
uz-Arab-AF

**Comment by tinohager** [comment]
Hi, i have publish a fix, based on your pull.

**Comment by landlogicit** [comment]
Good. Well done 

Inviato da iPad
