### ISSUE TITLE
Create Cart Error - Value of CartCreate is null

### ISSUE THREAD

**Issue by trnelson** [tinohager/Nager.AmazonProductAdvertising#38]
Hello!

Many thanks for your great package. I have been working successfully with it, but for some reason encountering an issue I can't seem to figure out. Was curious if you run into the same issue, and wondering if it has to do with any particular products I'm adding to cart. Here is the error message I'm getting when I enable logging in the wrapper:

```
<?xml version="1.0"?>
<CartCreateErrorResponse xmlns="http://ecs.amazonaws.com/doc/2009-03-31/"><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message></Error><RequestId>d1c8a874-e58b-4694-b217-55e347e4cf59</RequestId></CartCreateErrorResponse>
```

The result of the `CartCreate()` function is `null`.

It seems to happen when I try to create a cart with the following items (1 of each). I haven't yet narrowed down if it's one of these, but it may be. Mostly curious if this is a bug in your code or an issue on Amazon's end:
- 0061914177
- 1612680054
- 0321426770
- 3442217784
- 0307465357
- 159562015X
- 0887307280

Thank you!

**Comment by tinohager** [comment]
Hi
I have create a card with the same items, it works without problems.

**Comment by trnelson** [comment]
Hmm, I'm still having an issue. I'm able to create a cart sometimes, but not always, even when using the exact same collection of items.

It appears the issue may actually be on Amazon's side, as the XML error response indicates it's an internal error in their API.

I'm using the method `Nager.AmazonProductAdvertising.AmazonWrapper.CartCreate(System.Collections.Generic.IList<Nager.AmazonProductAdvertising.Model.AmazonCartItem>)` to create my cart, and passing in a list of `AmazonCartItem`. It seems if my list has more than 4-5 items on it, it fails about 50% of the time (error rate increases as I add more) with the error I noted and a `null` return from the function. 

I've tested several times and the list of items I'm sending is identical every time (exact same ASIN and quantity). Here is some sample code; when running this I am getting the error around 50% of the time. Forgive the ugly test code; I wanted to encapsulate everything in one place.

```
public async Task<object> CreateTestCart()
{
    var x = "";
    var err = "";

    var authentication = new AmazonAuthentication();
    authentication.AccessKey = ConfigurationManager.AppSettings.Get("Amazon.AccessKey");
    authentication.SecretKey = ConfigurationManager.AppSettings.Get("Amazon.SecretKey");
    var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.US, ConfigurationManager.AppSettings.Get("Amazon.AssociateTag"));
    wrapper.XmlReceived += (xml) => x = xml;
    wrapper.ErrorReceived += (errorResonse) => err = errorResonse.Error.Message;

    var items = new List<AmazonCartItem>();
    items.Add(new AmazonCartItem("0061914177"));
    items.Add(new AmazonCartItem("0887307280"));
    items.Add(new AmazonCartItem("0321426770"));
    items.Add(new AmazonCartItem("1612680054"));
    items.Add(new AmazonCartItem("159562015X"));
    items.Add(new AmazonCartItem("B01DN8TCEU"));
    items.Add(new AmazonCartItem("1592408419"));

    var result = wrapper.CartCreate(items);
    return new
    {
        Xml = x,
        Error = err,
        Result = result
    };
}
```

The result of this is either a fully populated result, or the following in the case of an error:

```
{
  "Xml": "<?xml version=\"1.0\"?>\n<CartCreateErrorResponse xmlns=\"http://ecs.amazonaws.com/doc/2009-03-31/\"><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message></Error><RequestId>f15ce738-2214-41db-9a3d-575e17aa1be0</RequestId></CartCreateErrorResponse>",
  "Error": "We encountered an internal error. Please try again.",
  "Result": null
}
```

**Comment by tinohager** [comment]
Is it work with the scratchpad?
http://webservices.amazon.com/scratchpad/index.html

**Comment by trnelson** [comment]
Ugh, same issue on the scratchpad (thank you for the suggestion!)

I guess the next best approach would be to to use multiple CartAdd requests, but I'm concerned about API limits, especially since this particular Associates account is new and doesn't have sales yet (still limited to 1 request per second.)

**Comment by trnelson** [comment]
One other thing I will look at shortly is whether I get the same error using Offer Listing ID instead of ASIN. I will let you know if I have any luck there. Do you have plans to add in a CartCreate option using Offer Listing IDs?

**Comment by trnelson** [comment]
Sorry for spamming, but just an update to let you know that I created a support request with AWS. Will post back if/when I hear anything.

**Comment by tinohager** [comment]
At the moment i not planed, it is a lot of work, if the the donations increase maybe i add new features...

**Comment by trnelson** [comment]
One final update here, since I heard back from Amazon's service team.

"Create the cart with one item and add items in the same cart using cart add operation."

This is clearly a limitation on their side with respect to the CartCreate API, and I wasn't given much more information. They did note that if I needed more TPS (transactions per second) to handle the additional queries I'd have to use, that I could request it for my account. Not sure how that will work out but I imagine it's on a case-by-case basis.

Hope this is helpful. Thank you again for your hard work @tinohager. I will need this functionality in my site so I may hack it into place as an urgent update, but if I can find the time I'll try to build it into your package and submit a pull request.
