### ISSUE TITLE
Condition and exception don't match in AmazonSearchItemOperation Skip(int) method

### ISSUE THREAD

**Issue by jordanwallwork** [tinohager/Nager.AmazonProductAdvertising#39]
if (value > 10)
    {
        throw new ArgumentOutOfRangeException("value", "value must be between 1 and 5");
    }

This looks wrong, should it be `if (value > 5)` or should the exception message be `"value must be between 1 and 10"`?

**Comment by tinohager** [comment]
It's dependent on the SearchIndex but yes the error is wrong.

http://docs.aws.amazon.com/AWSECommerceService/latest/DG/ItemSearch.html
Valid values: 1 to 10 (1 to 5 when search index is All)

**Comment by tinohager** [comment]
i have fix this issue
