### ISSUE TITLE
affiliate program link in response

### ISSUE THREAD

**Issue by DukeNuken** [tinohager/Nager.AmazonProductAdvertising#4]
Hello

I am using your lib and tring to get affiliate program link to the mp3 song.

`            var result = wrapper.Search("we will rock you", AmazonSearchIndex.MP3Downloads, AmazonResponseGroup.Large);`

it should be the link which I can put on my site for redirect on Amazon. I can make them manualy by that tool https://affiliate-program.amazon.com/gp/associates/network/build-links/individual/get-html.html?ie=UTF8&asin=B00138COL6&marketplace=amazon&quicklinks=1&subflow=sp_  but api response should return them too, right?

Duke

**Comment by tinohager** [comment]
yes, use the link in DetailPageURL

```c#
var result = wrapper.Search("we will rock you", AmazonSearchIndex.MP3Downloads, AmazonResponseGroup.Small);
var link = result.Items.Item[0].DetailPageURL;
```

**Comment by DukeNuken** [comment]
That code return link like that for your lib 

> http://www.amazon.com/We-Will-Rock-You/dp/B00138COL6%3FSubscriptionId%3DAKIAJXRE24SFKPKOIS4A%26tag%3Dnagerat-21%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00138COL6

and that the link which amazon give on site tool

> http://www.amazon.com/gp/product/B00138COL6/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00138COL6&linkCode=as2&tag=duke0e4-20&linkId=H6MIZIQOSWFXTY4H

Questions here:
1) Those links looks different. They have the same ID = B00138COL6, but SubscriptionId and camp not match. Is it still work? 
2) That item on site have 30 secounds demo which customer can listen before buy. Is there are any chance get link on that short mp3 sample?
3) Based on docs main param here "tag" which attach bonuses to account. Can i change it to mine?

Thanks a lot fir your help!

**Comment by tinohager** [comment]
Hello
With the new Version (1.0.8) the links have the correct format. To change the tag (associateTag) use the last parameter on AmazonWrapper

```csharp

var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.DE, "duke0e4-20");

```
