### ISSUE TITLE
Item search by url

### ISSUE THREAD

**Issue by NikasZalias** [tinohager/Nager.AmazonProductAdvertising#41]
Is it possible to search items by url?
For example I have following url: https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=nokia&rh=i%3Aaps%2Ck%3Anokia

And I want to get all items from first page. Is it possible in this library?

**Comment by tinohager** [comment]
sorry this library access direct the api and not parse the Website but it is possible to send a search request with a keyword
