### ISSUE TITLE
Download Website Example

### ISSUE THREAD

**Issue by WolfKof** [tinohager/Nager.AmazonProductAdvertising#44]
Where I can download the example code from the website and of course I'll invite you to a beer, you'll save a lot of time.

**Comment by MaximilianoRios** [comment]
I've been using this SDK for a while, all the code available is in the main page https://github.com/tinohager/Nager.AmazonProductAdvertising. There is nothing else there. If you need extra info I can show you how to implement it. I'm also coding the Walmart Api SDK in case you're interested.

**Comment by WolfKof** [comment]
Excellent, could you teach me how to implement it please?

**Comment by MaximilianoRios** [comment]
First at all, be sure you have an Amazon account and follow all the steps
to get the Api key. It takes a while to put all the info together and
obtain the key.
I will send you later some examples.

On May 31, 2017 1:12 PM, "WolfKof" <notifications@github.com> wrote:

Excellent, could you teach me how to implement it please?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tinohager/Nager.AmazonProductAdvertising/issues/44#issuecomment-305271389>,
or mute the thread

**Comment by WolfKof** [comment]
Very well, I already have the keys.

**Comment by MaximilianoRios** [comment]
Ok, the principles are very simple. You need to build an Authentication object with the Access/Secret keys:

            var authentication = new AmazonAuthentication();
            authentication.AccessKey = "your access key";
            authentication.SecretKey = "your secret key";

And add the associate tag once you build the wrapper:

            var associateTag = "your associate tag";
            AmazonWrapper wrapper = new AmazonWrapper(authentication, AmazonEndpoint.US, associateTag);

I assumed you're using the US endpoint, if you're not, change it for the one you need to use.

A very simple operation looks like this:

var searchOperation = wrapper.ItemSearchOperation("phrase to search", AmazonSearchIndex.All, AmazonResponseGroup.ItemAttributes | AmazonResponseGroup.Offers);

I'm using All as a search index (you can specify the ones you want to search in, like Babies, Electronics, etc) and I obtain ItemAttributes and Offers per item.
You can fine tune the search operation, in this case I need new items onlyL

searchOperation.Condition(ItemCondition.New);

Running the search is pretty simple, get a XML response and use the helper to obtain the object:

var xmlResponse = wrapper.Request(searchOperation);
var result = XmlHelper.ParseXml<ItemSearchResponse>(xmlResponse.Content);

The result can be null if there's an internal error or obtain a result but with errors:


if (result == null)
{
    // No response
 }
else
{
    // Response but there were errors
    if(result.Items.Request.Errors != null && result.Items.Request.Errors.Count() > 0)
    {
        // Do something
    }
}

If there are not errors you can navigate the list of items with:

foreach (var item in result.Items.Item)
{
    // do something with the items
}

item will contain the product, there are tons of properties so you have to add here whatever you need for your solution.

Hope it helped!

**Comment by WolfKof** [comment]
Thank you very much for your answer, I only have one problem with this line of code

`var Result = XmlHelper.ParseXml(xmlResponse.Content);`

In the error tells me the following:

> Arguments of type XmlHelper.ParseXML <T> (string) can not be inferred from the usage. Try specifying arguments of type Explicit.

Thank you very much for your valuable answers. Many will serve this to us.

**Comment by MaximilianoRios** [comment]
Replace it by the Generic version:
var result = XmlHelper.ParseXml<ItemSearchResponse>(xmlResponse.Content);

**Comment by WolfKof** [comment]
Seriously, thank you very much, I have understood perfectly how to use the Resource. I have managed to do what I needed, your collaboration was very helpful

**Comment by WolfKof** [comment]
Hello Look, I'm doing what I need pretty well, until I find a query that I could not solve, how do I look for an ASIN Article?

Also, how can I contact you? you have Skype?
