### ISSUE TITLE
Increase the number of items

### ISSUE THREAD

**Issue by paulorfnobrega** [tinohager/Nager.AmazonProductAdvertising#45]
Hi Tino Hager,

Thank you very much for your project. You are the best.

Paulo Nóbrega

**Comment by paulorfnobrega** [comment]
Hi Tino Hager,

In the website, how can i increase the number of items in the results?

Thanks,

Paulo Nóbrega

**Comment by MaximilianoRios** [comment]
I've been using this framework to make requests to Amazon and I didn't find anything to limit/change results. If I'm not wrong they are always paged in a default way. To implement N items in my code I just counted to a number of max items passed to a method and break the items iteration.

**Comment by paulorfnobrega** [comment]
Hi Maximiliano Rios,

Thanks for your response and help.

Paulo Nóbrega

**Comment by tinohager** [comment]
Hi

The limits of the items per request is limited by amazon. If you need more items you need multiple requests and work with paging.

**Comment by paulorfnobrega** [comment]
Hi Tino Hager, thanks for your response.
