### ISSUE TITLE
Multiple response groups do not work

### ISSUE THREAD

**Issue by Citizen-Thayne** [tinohager/Nager.AmazonProductAdvertising#46]
Given a valid BrowseNodeId, when I try to use multiple response groups with a lookup, the response comes back empty and with no error. 
```
AmazonWrapper wrapper 
var response = wrapper.BrowseNodeLookup(12345, AmazonResponseGroup.BrowseNodeInfo | AmazonResponseGroup.TopSellers)
```

It appears that `responseGroup.ToString()` contains a space between the response group names and is the source of the issue. When I do the following, I get the response I expect

``` 
var operation = new AmazonBrowseNodeLookupOperation();
operation.ParameterDictionary["ResponseGroup"] = (AmazonResponseGroup.BrowseNodeInfo | AmazonResponseGroup.TopSellers).ToString().Replace(" ", "");
```

**Comment by MaximilianoRios** [comment]
If you fix it and push it let us know, I have to use this feature soon.

**Comment by tinohager** [comment]
I have upload the new version
