### ISSUE TITLE
Get back Error code in case of wrong credentials

### ISSUE THREAD

**Issue by nafberger** [tinohager/Nager.AmazonProductAdvertising#54]
Hi Mr. Nager, I am using your code in a program, it works great, my question is, how can I get back the correct error message from amazon in case the user input wrong credentials like this one? 

![screenshot_1](https://user-images.githubusercontent.com/26122027/30836968-a31084bc-a22f-11e7-9f91-2539b1eb83c4.png)

I tried wrong credentials with your code, namely: `var result = wrapper.Lookup(testAsin)` but the result is just null, i need more info because null can be due to more then one type off error

**Comment by tinohager** [comment]
You subscribe the error event "ErrorReceived "

var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.US, "nager-20");
wrapper.ErrorReceived += (errorResonse) => { System.Diagnostics.Debug.WriteLine(errorResonse.Error.Message); };
var result = wrapper.Lookup(new string[] { "B00OQVZDJM", "B00ZV9RDKK" });

**Comment by nafberger** [comment]
Thanks, I will try it and report back. BTW are you familiar with devextreme

**Comment by nafberger** [comment]
Cool it works
