### ISSUE TITLE
Old API Version

### ISSUE THREAD

**Issue by speige** [tinohager/Nager.AmazonProductAdvertising#55]
AmazonSign.cs

function GetRequestArguments

should have this line added:

requestArgs["Version"] = "2013-08-01";

Or, ideally there should be a parameter in the constructor of AmazonWrapper that allows specifying the api version

**Comment by tinohager** [comment]
What is your opinion according to the current version?
What is the advantage when this value is changeable?

**Comment by speige** [comment]
Some properties aren't returned with the older api version, because they were added afterwards. For example, products related to instant video have extra properties.

**Comment by tinohager** [comment]
I think the model of the class is also invalid and both must updated?

**Comment by speige** [comment]
Yes, you're correct. The documentation lists the response objects here http://docs.aws.amazon.com/AWSECommerceService/latest/DG/CHAP_response_elements.html

If you're using method public AmazonItemResponse Search(string search, AmazonSearchIndex searchIndex = AmazonSearchIndex.All, AmazonResponseGroup responseGroup = AmazonResponseGroup.Large), then the updated model makes a difference.

In my case I'm using public ExtendedWebResponse Request(AmazonOperationBase amazonOperation), which gives me XML. So, I'm able to read the missing properties.

**Comment by swiseken** [comment]
Hey @tinohager, do you think you'll be updating the library for the new version of the API along with adding the Cart Methods?

**Comment by tinohager** [comment]
At the moment i have no plans. If you need it urgently you can send the changes gladly.


Tino

**Comment by Magnamarum** [comment]
Are you planning to add batch query ? https://docs.aws.amazon.com/AWSECommerceService/latest/DG/BatchandMultipleOperationRequests.html

**Comment by tinohager** [comment]
I have update the version https://github.com/tinohager/Nager.AmazonProductAdvertising/commit/e7ab064b016949f5c6d74a01a33996d0e1e253af
