### ISSUE TITLE
Amazon Australia Marketplace

### ISSUE THREAD

**Issue by apavelm** [tinohager/Nager.AmazonProductAdvertising#57]
Amazon added Australia as Seller accessible marketplace. Could you please add AU marketplace (A39IBJ37TRP1C6) to the list of endpoints.

**Comment by tinohager** [comment]
At the moment shows not ready
https://www.ctrl.blog/entry/amazon-affiliate-australia

**Comment by apavelm** [comment]
@tinohager Seems llike Amazon Australia started to work. But I'm not sure about affilate program.

**Comment by andreigec** [comment]
affiliate program is up
