### ISSUE TITLE
Results often coming back empty

### ISSUE THREAD

**Issue by roror409** [tinohager/Nager.AmazonProductAdvertising#58]
When I'm invoking the Multi-Item lookup as of a few days ago my return has been failing at a very large pace.  I'm getting an absolute ton of "System.NullReferenceException: Object reference not set to an instance of an object"  error messages when trying to read the results of the query.  When I'm debugging I'm not getting the same message.  In my code, I have a built-in wait when it's running so that Amazon is only queried once every second as to not pass up my threshold.  So I know it's not that I'm exceeding my allowed API requests in production.  Any ideas as too what might be going on?  Is anyone else having this issue?

**Comment by ZoomStop** [comment]
I struggled with issues like this until I used the error wrapper Tino provides. Try it and see what error message Amazon is telling you...

```
var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.US, "affiliate-tag");
wrapper.ErrorReceived += (errorResonse) => { do somehting with errorResponse.... };
```

**Comment by roror409** [comment]
Thank you for the feedback.  I hadn't been using that error wrapper.  It's helping immensely.
