### ISSUE TITLE
Sometimes results not coming back

### ISSUE THREAD

**Issue by rgsoft** [tinohager/Nager.AmazonProductAdvertising#59]
Hi

I'm finding sometimes the result coming back is null even though I'm searching for the same ISBN - is there something that may affect this.  Is there a time restriction between searches? - I'm scanning in the ISBN's using bar code scanner. Thanks.

`var authentication = new AmazonAuthentication();
authentication.AccessKey = "key";
authentication.SecretKey = "secret";
var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.UK, "xxxx-xx");

var result = wrapper.Lookup(ISBN13);

if (result == null || result.Items == null || result.Items.Item == null)
{
	LoadProperty(TitleProperty, "Not Found");
	return;
}`

**Comment by ZoomStop** [comment]
The Amazon PA API limits you to one call per second. If you are on a provisional API key and not accepted into the associate program then you may also see your requests throttled to one per 10 seconds after you do 8,640 calls. 

Realistically right now it would seem on a provisional key I am getting about one call every 5 seconds on average (they seem to randomize the delay?). On a normal key you should be able to get one call a second all day every day (or more if your limit has been increased due to sales).

**Comment by rgsoft** [comment]
Thanks - I have a full/normal key so I guess so long as I'm slower than 1 search a second then it will work - thanks

**Comment by rgsoft** [comment]
Is there a way to determine if a search has been blocked (as in the above scenario) as opposed to the lookup/search just not finding an item?

**Comment by ZoomStop** [comment]
Really your best bet is it use the error wrapper the framework provides. It will let you see the specific error coming back from Amazon. 

var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.US, "affiliate-tag");
wrapper.ErrorReceived += (errorResonse) => { do something with errorResponse.... };

**Comment by rgsoft** [comment]
Thanks will look into that.  Finally, the limit is based on requests from an IP address  - outside of my experience/knowledge here - if two or more pc's are searching on the same site/network then is the IP address coming from pc or the network?  i.e is the 1 search per second based on each pc or total searches per second on that network (all pc's searching)?

**Comment by ZoomStop** [comment]
That would be based on IP, but that would be your internet IP. So all the systems connecting to the internet through the same broadband connection would be the same IP address to Amazon. You could run VPN software though on one or more of the systems to cloak their location, but Amazon's policy is one call per second per account. So you would need additional accounts also. It can get rather complicated and turn into a rabbit hole haha.

**Comment by rgsoft** [comment]
Thanks for all contributions

⁣Richard Griffiths
(Sent from mobile phone)

**Comment by tinohager** [comment]
Additional Informaton

http://docs.aws.amazon.com/AWSECommerceService/latest/DG/TroubleshootingApplications.html
_Each account used to access the Product Advertising API is allowed an initial usage limit of 1 request per second*. Each account will receive an additional 1 request per second (up to a maximum of 10) for every $4,600 of shipped item revenue driven in a trailing 30-day period (about $0.11 per minute)._
