### ISSUE TITLE
BrowseNodes

### ISSUE THREAD

**Issue by SergeySypalo** [tinohager/Nager.AmazonProductAdvertising#6]
Hi Tino,

Are you planning to implement BrowseNodeLookup operation to retrieve various info like child nodes or best sellers for give Category/BrowseNodeID ?

Br, Sergey

**Comment by tinohager** [comment]
Hello Sergey

Yes is planned in one of the next releases.

best regards
Tino

**Comment by tinohager** [comment]
Hi

I have add the method for BrowseNodeLookup.

best regards
Tino
