### ISSUE TITLE
Amazon API submitting requests too quickly

### ISSUE THREAD

**Issue by boriside** [tinohager/Nager.AmazonProductAdvertising#61]
Hi, 

sometimes I get "Amazon API submitting requests too quickly" in the XML response.
I am using the newest version of the library. 

Cheers

**Comment by ProNotion** [comment]
I've hit the same but I'm not sure it is the responsibility of this API wrapper to throttle the calls to the web service. 

> The request limit for each account is calculated based on revenue performance. Each account used to access the Product Advertising API is allowed an initial usage limit of 1 request per second*. Each account will receive an additional 1 request per second (up to a maximum of 10) for every $4,600 of shipped item revenue driven in a trailing 30-day period (about $0.11 per minute). 

The above was quoted from the [Amazon Docs](https://docs.aws.amazon.com/AWSECommerceService/latest/DG/TroubleshootingApplications.html)

**Comment by ProNotion** [comment]
Also, in case it helps I want to look at maybe integrating something like this API Throttler to better manage it: https://github.com/stefanprodan/WebApiThrottle

**Comment by boriside** [comment]
Thinking about it it, it could be my fault as well, because I do (in pseudo
code):


var x = wrapper.lookupBrowseNodeOperation(nodeId, TopSellers)

foreach(x.Asin)
    var item = wrapper.lookup(x.Asin)
    //do something with item

I maybe need a sleep function after looking up an item. Or is it a better
way to do it?



*Boris Idesman*

*Mobile:  +49 160  276 2085*

*   +359 886 341 568*

**Comment by boriside** [comment]
Thinking about it it, it could be my fault as well, because I do (in pseudo
code):


var x = wrapper.lookupBrowseNodeOperation(nodeId, TopSellers)

foreach(x.Asin)
    var item = wrapper.lookup(x.Asin)
    //do something with item

I maybe need a sleep function after looking up an item. Or is it a better
way to do it?

>
>

**Comment by ZoomStop** [comment]
You should pass a List<String> of 10 ASINs for starters, to maximize the API. And then yes a sleep function but the sleep duration will change after 8,640 requests. You can message me on here if you want, but Nager.AmazonProductAdvertising is working properly so opening an issue isn't the best way to get help.

**Comment by ProNotion** [comment]
Turns out that the throttle package above was not what I was looking for I think it is geared more towards throttling usage of your own API's rather than throttle client usage of another API.

I'm interested to hear how others are handling this. For the moment I am using a Nuget package called [RateLimiter](https://www.nuget.org/packages/RateLimiter/) which is so far working out OK.

**Comment by boriside** [comment]
@ZoomStop, how does one "pass a List<String> of 10 ASINs"

**Comment by boriside** [comment]
@ZoomStop Could you please elaborate on "pass a List<String> of 10 ASINs"

**Comment by ZoomStop** [comment]
I just meant with the Amazon API (and this framework), you can pass an ASIN as a string and it will respond with one item in the response object. But if you pass a List<String> of 10 ASINs (and I believe an Array of 10 works fine also IIRC) then you will get an array of 10 responses back. So that is step 1 to maximizing your API calls.

**Comment by boriside** [comment]
OK, I have the following code, that somethimes result in "too many requests" and crashes:
`        public List<AmzItem> PerformSearchNodes(long nodeId)
        {
            var searchOperation = wrapper.BrowseNodeLookupOperation(nodeId, AmazonResponseGroup.TopSellers);
            var xmlResponse = wrapper.Request(searchOperation);
            var itemsInXML = XmlHelper.ParseXml<BrowseNodeLookupResponse>(xmlResponse.Content);
            var itemsASINsStrings = new List<string>();
            var counter = 0;
            try
            {
                //we take only up to 8 items!
                foreach (var itemForASIN in itemsInXML.BrowseNodes.BrowseNode.TopSellers.TopSeller)
                {
                    if (counter < 8 && itemForASIN.ASIN != null)
                    {
                        itemsASINsStrings.Add(itemForASIN.ASIN);
                    }
                    counter++;
                }
                var tenItems = wrapper.Lookup(itemsASINsStrings);
                foreach (var z in tenItems.Items.Item)
                {
                    if (z != null && z.ItemAttributes.Title != null && z.LargeImage != null && z.DetailPageURL != null)
                        if (z.LargeImage.URL != null)
                        {
                            {
                                if (z.ItemAttributes.ListPrice != null)
                                {
                                    amzItemsList.Add(new AmzItem(z.ItemAttributes.Title, z.ItemAttributes.ListPrice.FormattedPrice, z.LargeImage.URL, z.DetailPageURL));
                                }
                                else
                                {
                                    amzItemsList.Add(new AmzItem(z.ItemAttributes.Title, "Price: Check offer", z.LargeImage.URL, z.DetailPageURL));
                                }
                            }
                        }
                }
            }catch(Exception exc)
            {
                amzItemsList.Add(new AmzItem("Error AmzAdvApiComm:" + exc.Message, exc.StackTrace, "", ""));
            }                
            return amzItemsList;
        }`

What is wrong with it? Thanks!
