### ISSUE TITLE
Getting incorrect prices while using Lookup method

### ISSUE THREAD

**Issue by umarch-rltsquare** [tinohager/Nager.AmazonProductAdvertising#63]
I have been enjoying using this library, but unfortunately I went through some problem. I am getting prices from amazon with the *LookUp* method as:
`var result = wrapper.Lookup("B0148GGBG8",` AmazonResponseGroup.Large)`

so, this is how I get the price:

`string price = result.Items.Item[0].ItemAttributes.ListPrice.FormattedPrice;`

Has anyone faced the same issue? I will really appreciate if you guys can provide a quick fix?

**Comment by ZoomStop** [comment]
What AmazonEndpoint are you using in your wrapper configuration?
Do you have an example ASIN? Have you used the [scratchpad](https://mws.amazonservices.com/scratchpad/index.html) to validate the price is incorrect?

**Comment by umarch-rltsquare** [comment]
Ok here is the list that I am fetching

`price from api | original price | asin` and in the right single column I have asins for which I have wrong price


<img width="974" alt="screen shot 2018-01-30 at 6 22 37 pm" src="https://user-images.githubusercontent.com/26297709/35568432-c8583cf0-05ea-11e8-91e5-beea99c54b16.png">


This is what I am doing:

```
using Nager.AmazonProductAdvertising;
using Nager.AmazonProductAdvertising.Model;
using Nager.AmazonProductAdvertising.Operation;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            var authentication = new AmazonAuthentication();
            authentication.AccessKey = "my key";
            authentication.SecretKey = "my secret key";

            var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.US, "xxxxxx");

            List<string> itemsIds = File.ReadAllLines("asins.txt").ToList();

            List<AmazonItemResponse> longList = new List<AmazonItemResponse>();
            List<AmazonItem> shortList = new List<AmazonItem>();

            foreach (var itemId in itemsIds)
            {
                var result = wrapper.Lookup(itemId, Nager.AmazonProductAdvertising.Model.AmazonResponseGroup.Large);
                Thread.Sleep(TimeSpan.FromSeconds(2));
                longList.Add(result);

                string price = "";
                Nager.AmazonProductAdvertising.Model.OfferListing offerListing = null;
                string asin = "";

                try { asin = result.Items.Item[0].ASIN; } catch { }
                try { offerListing = result.Items.Item[0].Offers.Offer[0].OfferListing[0]; } catch { }
                try { price = result.Items.Item[0].ItemAttributes.ListPrice.FormattedPrice; } catch { }

                AmazonItem ai = new AmazonItem { Price = price, ASIN = asin, OfferListing = offerListing };
                shortList.Add(ai);
            }

            try
            {
                File.Delete("output.txt");
            }
            catch (Exception)
            {

                throw;
            }

            foreach(var row in shortList)
            {
                string text = row.ASIN + "|" + row.Price;
                File.AppendAllText("output.txt", text + Environment.NewLine);
            }
            //wrapper.Request()
            //var temp = wrapper.Lookup("B000COYPTG", AmazonResponseGroup.Large);
        }
    }

    public class AmazonItem
    {
        public string Price { get; set; }
        public string ASIN { get; set; }
        public Nager.AmazonProductAdvertising.Model.OfferListing OfferListing { get; set; }
    }
}

```

**Comment by umarch-rltsquare** [comment]
@ZoomStop  let me know if you need anything from me as well, my amazon end point is `US`

**Comment by ZoomStop** [comment]
Everything looks good. How long do you let elapse between when you pull the data with the API and you double check the price on the web? Looks like your API pricing is a little old, I see most of your API prices as valid prices in the Amazon history according to Keepa, when there is a variance. In other words it just looks like the prices are changing slightly between when you scan them with the API and validate them on the web.

**Comment by umarch-rltsquare** [comment]
I am putting explicit wait of 2 seconds, before I was having no wait due to which I was having some responses as null. 
The prices are wrong, even if I check them frequently without no delay they are different on web and on code. I am stuck in middle of something unfortunately, is there a way we can have it working perfect?

**Comment by ZoomStop** [comment]
What I meant was how long between when you pull the price on the API and then check on the web? Can you open the PA API scratchpad in one window and pull price A off the API and then see price B on Amazon? Just saying for the few items I spot checked, where you had a price difference there was that price in history, just not currently. 
I run this on various programs 24x7 and the prices have always been accurate to the date/time I pulled them.

**Comment by umarch-rltsquare** [comment]
I tested in scratchpad the same time, the prices in scratchpad are fine but in api resposne I am getting wrong. Is there anything missing in code which I am not specifying?

Here is the asin i tried:
B0148GGBG8

in scratchpad: $12.49
through this library: $15.99
This problem is giving me shocks

**Comment by umarch-rltsquare** [comment]
Can you try my code? I can provide you file including asins as well.

**Comment by tinohager** [comment]
I have contacted the Amazon Partner Team and wait for a response.

**Comment by ZoomStop** [comment]
Your code is pulling the ListPrice which is correct at $15.99. You want to pull the actual new or used price: 

`result.Items.Item[0].OfferSummary.LowestNewPrice.FormattedPrice` 
or if you want the used price 
`result.Items.Item[0].OfferSummary.LowestUsedPrice.FormattedPrice` 
instead of the `Items.Item[0].ItemAttributes.ListPrice.FormattedPrice` which is exactly what it says, the List Price.

See the Amazon XML response for your example ASIN below.
https://pastebin.com/PWweM1mX

**Comment by umarch-rltsquare** [comment]
@ZoomStop what I understood with your comment is that we may have prices in different nodes in api response, is there a way I can have a specific node/condition where I can get exactly same price as I get in `scratchpad` or `Amazon Website` ?

**Comment by ZoomStop** [comment]
You are getting the same prices in the scratchpad and the API, they are the same thing. I think you may be confusing the price in for Item[0], lowest price, etc is not necessarily the BuyBox price. As far as I know you cannot determine BuyBox reliability with the PA API. You get pull the lowest new and used prices, and the BB is usually the lowest new price, but not always. If you need to know the actual BB price and can't scrape it, the only API I know of that would have it is the Keepa API.
That is a good API, but is not free. There isn't a nice C# framework like tinohager made for the PA API, but I have working code you can use if you get to that point.

**Comment by umarch-rltsquare** [comment]
@ZoomStop I will highly appreciate if we can talk on my requirement, can you give me your email here? I am ready for the paid help as well if you need that.
If you feel some confidential issues, please send me your email at `umarch06@gmail.com`.

**Comment by ZoomStop** [comment]
Got it, I reached out in email.
Tino pretty sure you can close this issue.

**Comment by umarch-rltsquare** [comment]
@ZoomStop thank you for the response, I will close the issue now.
