### ISSUE TITLE
Search Multiple Search Indexes with a single ItemSearchOperation

### ISSUE THREAD

**Issue by ProNotion** [tinohager/Nager.AmazonProductAdvertising#64]
As far as I can tell it's not possible to search multiple categories. I tried the following:

I tried adding [Flags] to the AmazonSearchIndex enum and using the code below but still no luck:
```
{
	var searchIndexes = searchIndex.Split(new [] {"," }, StringSplitOptions.RemoveEmptyEntries);
	foreach (var s in searchIndexes)
	{
		selectedIndex |= (AmazonSearchIndex)Enum.Parse(typeof(AmazonSearchIndex), s);
	}
}
var searchOperation = wrapper.ItemSearchOperation(term, selectedIndex, AmazonResponseGroup.ItemAttributes);
```

Any ideas?

**Comment by ZoomStop** [comment]
The Amazon PA API Search indices do not allow for multiple values to be specified.
https://docs.aws.amazon.com/AWSECommerceService/latest/DG/SearchIndices.html

If you look at the [Item Search on the Amazon scratchpad](http://webservices.amazon.com/scratchpad/index.html?rw_useCurrentProtocol=1) you will see that for SearchIndex you can only select no value (search all) or one value (search one).

Being able to selectively query groups of departments would be super powerful, and unfortunately is not available.

**Comment by ProNotion** [comment]
OK thanks for your input on this. I guess I'll have to perform multiple searches and join the results which could get interesting when it comes to paging.
