### ISSUE TITLE
add multiple ResponseGroup in request

### ISSUE THREAD

**Issue by umarch06** [tinohager/Nager.AmazonProductAdvertising#65]
There are some cases when I need to send multiple response groups in ItemLookUp method, can you please add that in code as well? I have a busy schedule this week else I would have done it and had made a pull request too.

**Comment by umarch06** [comment]
@tinohager  [here ](https://github.com/tinohager/Nager.AmazonProductAdvertising/pull/66)is the pull request, I changed some of the existing functions signatures as well

**Comment by tinohager** [comment]
@umarch06 Thanks, i check the pull request the next days... I am also very busy at the moment

**Comment by umarch06** [comment]
thanks @tinohager let me know if you need anything from me.
