### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Oxsit** [tinohager/Nager.AmazonProductAdvertising#67]
Hi,

The code you added does not work, https://prnt.sc/iddyra.
another error; https://prnt.sc/ide0rw - https://prnt.sc/ide0x5

Error Code: "Your ResponseGroup parameter is invalid. Valid response groups for ItemLookup requests include ['Request','ItemIds','Small','Medium','Large','Offers','OfferFull','OfferSummary','OfferListings','PromotionSummary','PromotionDetails','VariationMinimum','VariationSummary','VariationMatrix','VariationOffers','Variations','TagsSummary','Tags','ItemAttributes','MerchantItemAttributes','Tracks','Accessories','EditorialReview','SalesRank','BrowseNodes','Images','Similarities','Subjects','Reviews','ListmaniaLists','SearchInside','PromotionalTag','SearchBins','AlternateVersions','Collections','RelatedItems','ShippingCharges','ShippingOptions'].""

Can you help me?

Tnks

**Comment by Oxsit** [comment]
when can you review it? tnks.

**Comment by tinohager** [comment]
The example is fixed
