### ISSUE TITLE
Itemlookup Merchant Name & old api version

### ISSUE THREAD

**Issue by hasbimuharip** [tinohager/Nager.AmazonProductAdvertising#68]
Itemlookup can get **Merchant Names** normally but this feature doesnt exist here.

This must be added as parameter for request `"Condition", "All"` 
and api version section need to be optional or deleted in order to request with default api version which is `2011-08-01.`

Currently used version is `requestArgs["Version"] = "2009-03-31";` which is older and not support some operations as i mentioned above "item lookup merchant name".

According to product advertising documents:

>Product Advertising API enables you to specify the version of the WSDL you want to use. This functionality ensures that future enhancements and changes to Product Advertising API WSDLs will not be intrusive to your applications. For example, when Product Advertising API adds new elements to its WSDL, applications that validate against an older Product Advertising API WSDLs will not be affected.

> The AWSECommerceService directory contains all of the Product Advertising API WSDL versions. You use the Version parameter in REST requests to specify the version of the WSDL you want to use. The default version is 2011-08-01. If you want to use a different WSDL version, including the latest, you must specify it in each request, for example, in REST.

[https://docs.aws.amazon.com/AWSECommerceService/latest/DG/Versioning.html](url)

**Comment by tinohager** [comment]
duplicate issue https://github.com/tinohager/Nager.AmazonProductAdvertising/issues/55

**Comment by tinohager** [comment]
update the version https://github.com/tinohager/Nager.AmazonProductAdvertising/commit/e7ab064b016949f5c6d74a01a33996d0e1e253af
