### ISSUE TITLE
Question About Paging When Using Wrapper.Search() Method

### ISSUE THREAD

**Issue by nafberger** [tinohager/Nager.AmazonProductAdvertising#70]
Hi Mr. Nager, thanks for your code, we use it in our project.

I am trying to start to use the Wrapper.Search() method (it returns an AmazonItemResponse object on which we built our code), but it gives back only 10 results, how do we page to the next results. 

On the main GitHub page, it says to use the ItemSearchOperation method but this doesn't give back an AmazonItemResponse object but just XML. any advice. Huge Thanks

**Comment by ianhoppes** [comment]
You have to deserialize the XML into an ItemSearchResponse using the following helper method:

`var result = XmlHelper.ParseXml<ItemSearchResponse>(xmlResponse.Content);`
