### ISSUE TITLE
Unable to get deals from browse node

### ISSUE THREAD

**Issue by boriside** [tinohager/Nager.AmazonProductAdvertising#73]
[https://www.amazon.de/b/ref=gbph_ftr_m-3_b87d_page_7?_encoding=UTF8&node=3849601&gb_f_first=enforcedCategories:562066,dealStates:AVAILABLE%252CWAITLIST%252CWAITLISTFULL%252CUPCOMING,dealTypes:DEAL_OF_THE_DAY%252CBEST_DEAL%252CLIGHTNING_DEAL%252CCOUPON_DEAL,page:7,sortOrder:BY_SCORE,dealsPerPage:5&pf_rd_p=1b9a592b-2554-4029-bf27-dcc49493b87d&pf_rd_s=merchandised-search-3&pf_rd_t=101&pf_rd_i=3849601&pf_rd_m=A3JWKAKR8XB7XF&pf_rd_r=JGM7V40ENYXAXKQXB7AP&ie=UTF8](url) contains deals but I am unable to get them. Does the library provide any way to access deals, or are there any other ways to achieve it? Thanks.

**Comment by tinohager** [comment]
I think it's not possible, you can contact amazon support...
