### ISSUE TITLE
Optional fields in class ItemAttributes

### ISSUE THREAD

**Issue by JonesAbramoff** [tinohager/Nager.AmazonProductAdvertising#76]
Hi,

Please update the ItemAttributes class definition considering optional fields.

You may test with ASIN B07524W5P3 in USA Amazon.

The deserialization of Item Lookup returned Itemattributes as Nothing but that was incorrect.
Only a few attributes is missing, like EAN.

Thanks,

Jones Abramoff

**Comment by tinohager** [comment]
Amazon has blocked my test account for USA. I can not do any tests more. As long this stays my motivation is not very big to optimize anything.

**Comment by JonesAbramoff** [comment]
Sorry to hear that.

**Comment by tinohager** [comment]
You can post the xml response of TestUI (Download the full source code). With this response i can check the deserialization.

![image](https://user-images.githubusercontent.com/8215186/39268981-a26007ec-48d1-11e8-924c-b730fd87e5fa.png)

**Comment by JonesAbramoff** [comment]
ok
[nager_issue_76.zip](https://github.com/tinohager/Nager.AmazonProductAdvertising/files/1948794/nager_issue_76.zip)

**Comment by tinohager** [comment]
I check this the week after next.

**Comment by tinohager** [comment]
Your XML response contains no EAN information

**Comment by JonesAbramoff** [comment]
Hi,

The problem was exactly that it should return Itemattributes with the other fields even without ean.

Thanks

**Comment by tinohager** [comment]
try change the response group to large

Am 07.05.2018 um 23:38 schrieb JonesAbramoff <notifications@github.com<mailto:notifications@github.com>>:


Hi,

The problem was exactly that it should return Itemattributes with the other fields even without ean.

Thanks
