### ISSUE TITLE
Is there any way to lookup the best item basis of bestseller, mover and shakers, hot and new.

### ISSUE THREAD

**Issue by anirugu** [tinohager/Nager.AmazonProductAdvertising#79]
As you can see,
https://www.amazon.com/gp/movers-and-shakers/ref=zg_bsms_unv_bt_0_bt_1
There are few options on the page, movers, and shakers, bestsellers, newly released, most wish or most gifted.

Please check.

**Comment by ZoomStop** [comment]
Keepa sells access to real time data like that and they have an API.

**Comment by tinohager** [comment]
Check this http://webservices.amazon.com/scratchpad/index.html

Or contact amazon self, thanks
