### ISSUE TITLE
Search method always returns null

### ISSUE THREAD

**Issue by tornikegomareli** [tinohager/Nager.AmazonProductAdvertising#81]
```
var authentication = new AmazonAuthentication();
authentication.AccessKey = "accesskey";
authentication.SecretKey = "secretkey";

var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.US, "nager-20");
var result = wrapper.Search("canon eos", AmazonSearchIndex.Electronics, AmazonResponseGroup.Large);
```
I've registered on amazon, get my accessKey and secretKey but every time result is null.

**Comment by tinohager** [comment]
Check the response of error

	var authentication = new AmazonAuthentication();
	authentication.AccessKey = "accesskey";
	authentication.SecretKey = "secretkey";

	var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.US, "nager-20");
	wrapper.XmlReceived += (xml) => { System.Diagnostics.Debug.WriteLine(xml); };
	wrapper.ErrorReceived += (errorResonse) => { System.Diagnostics.Debug.WriteLine(errorResonse.Error.Message); };
	var result = wrapper.Lookup(new string[] { "B00OQVZDJM", "B00ZV9RDKK" });
