### ISSUE TITLE
Amazon Australia

### ISSUE THREAD

**Issue by JonesAbramoff** [tinohager/Nager.AmazonProductAdvertising#82]
Hi,

Would you please include Amazon Australia ?

Thanks,

Jones Abramoff

**Comment by tinohager** [comment]
The new nuget package is available

**Comment by JonesAbramoff** [comment]
Thanks a lot !!!

From: Tino Hager 
Sent: Thursday, June 07, 2018 6:04 AM
To: tinohager/Nager.AmazonProductAdvertising 
Cc: JonesAbramoff ; Author 
Subject: {Disarmed} Re: [tinohager/Nager.AmazonProductAdvertising] Amazon Australia (#82)

The new nuget package is available
