### ISSUE TITLE
AmazonSearchIndex not response from AmazonEndopoint.BR

### ISSUE THREAD

**Issue by WagnerW** [tinohager/Nager.AmazonProductAdvertising#86]
Hi, my error "The value you specified for SearchIndex is invalid Valid values include 'All', **'HomeImprovement'**, 'Kitchen', 'PCHardware', 'OfficeProducts', 'Electronics', 'MobileApps', 'KindleStore' , 'Books', **'Home'**, 'VideoGames', from AmazonEndpoint.BR (Brazil).

HomeImprovement == AmazonSearchIndex.Tools // not working.
Home == AmazonSearchIndex.HomeGarden // not working.

I'm trying to use the "Tools and Building Materials" category and if it is "ALL" it responds. Thanks.

**Comment by tinohager** [comment]
Hi i can not add for every country own SearchIndexes, this is a problem of amazon api.
