### ISSUE TITLE
Flash offers

### ISSUE THREAD

**Issue by molidestroyer** [tinohager/Nager.AmazonProductAdvertising#87]
Hi, 

Thanks a lot for the wrapper, but there is something that i miss, I'm not able to found the lowest price when there is a flash offer on the article. 
There is any way to get it?

Regards

**Comment by tinohager** [comment]
I think this is not possible but you can write the amazon support directly over the partnernet portal.

**Comment by molidestroyer** [comment]
Great, thanks, I was not able to identify if there was any property to do so. I'll ask them just in case. Thanks a lot for your amazing wrapper!
