### ISSUE TITLE
Could not install package into NetFramework version 4.0

### ISSUE THREAD

**Issue by shaaraa** [tinohager/Nager.AmazonProductAdvertising#89]
install-package : Could not install package 'Nager.AmazonProductAdvertising 1.2.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that ar
e compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ install-package Nager.AmazonProductAdvertising
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by tinohager** [comment]
Please update your project to .net Framework 4.5
![image](https://user-images.githubusercontent.com/8215186/48334156-f1529880-e659-11e8-95f4-eca9ac973dc6.png)

**Comment by shaaraa** [comment]
thank u @tinohager 👍
