### ISSUE TITLE
empty Result

### ISSUE THREAD

**Issue by shaaraa** [tinohager/Nager.AmazonProductAdvertising#90]
when i run the search result is empty and
i get this error on wrapper.ErrorReceived:
Results View = Expanding the Results View will enumerate the IEnumerable
Method = {Void <Search>b__2(Nager.AmazonProductAdvertising.Model.AmazonErrorResponse)}

**Comment by tinohager** [comment]
:) you must expand the list with the errors, the error is behind this

**Comment by shaaraa** [comment]
I expanded alot it gave me the same error. Maybe im expanding wrong. Which one should i expand?

**Comment by tinohager** [comment]
The AmazonErrorResponse.

**Comment by tinohager** [comment]
No :)

Please add your code example

**Comment by shaaraa** [comment]
@tinohager Hello Tino.im using your code.

`var authentication = new AmazonAuthentication();
authentication.AccessKey = "accesskey";
authentication.SecretKey = "secretkey";

var wrapper = new AmazonWrapper(authentication, AmazonEndpoint.US, "nager-20");
var result = wrapper.Lookup("B00BYPW00I");`

**Comment by shaaraa** [comment]
@tinohager would you please Remote and see what happend?

**Comment by shaaraa** [comment]
@tinohager Hello?
