### ISSUE TITLE
Missing Attribute - AvailabilityAttributes\AvailabilityType

### ISSUE THREAD

**Issue by roror409** [tinohager/Nager.AmazonProductAdvertising#92]
When using this API you can get to item.Offers.Offer[0].OfferListing[0].Availability but now when querying Amazon directly from the scratchpad there appears to be a new path to this information.  The new information would be item.Offers.Offer[0].OfferListing[0].AvailabilityAttributes.AvailabilityType but that information is not available through the Nager.AmazonProductAdvertising code.  Am I missing something or is that information just not available through Nager.AmazonProductAdvertising ?  Thank you.

**Comment by roror409** [comment]
Also missing the EligibilityRequirementType attribute.  Thanks for the feedback.

**Comment by tinohager** [comment]
A new nuget package is available

**Comment by roror409** [comment]
Thank you for your help.  I had looked for an update before but it didn't find one.  I looked after your message and it was there now.  Strange.
