### ISSUE TITLE
Minimum Order Quantity (not quantity)

### ISSUE THREAD

**Issue by roror409** [tinohager/Nager.AmazonProductAdvertising#93]
I'm trying to find out if there is a way with Nager to see if a listing has a minimum order quantity to be purchased.  I'm able to find the quantity available without any issues.  That is not what I'm asking about just to be clear.  There are some items such as https://www.amazon.com/Blue-Buffalo-Treats-Kitty-YumsTuna/dp/B008OV9814 , that for a one time purchase, require you buy a minimum of 3 of these items.  I can't seem to figure out how to retrieve that information.  Thank you for the info.

**Comment by tinohager** [comment]
I can only access the same data as the scratchpad.
