### ISSUE TITLE
now work

### ISSUE THREAD

**Issue by TheXeon81** [tinohager/Nager.AmazonProductAdvertising#95]
i receive this error:

<ItemSearchErrorResponse xmlns="http://ecs.amazonaws.com/doc/2009-03-31/">
  <Error>
    <Code>RequestThrottled</Code>
    <Message>AWS Access Key ID: xxxxxxxxxxxxxxxxxxxxx. You are submitting requests too quickly. Please retry your requests at a slower rate.</Message>
  </Error>
  <RequestID>fa193eaf-0b4b-xxxx-xxxx-83291b303b4d</RequestID>
</ItemSearchErrorResponse>

when press SEARCH button ...

**Comment by elarrieux** [comment]
Hi! That's not a problem with the library but a problem with your application. Amazon throttles you if you don't have any sales. Please refer to: https://docs.aws.amazon.com/AWSECommerceService/latest/DG/TroubleshootingApplications.html
