### ISSUE TITLE
UAE Support

### ISSUE THREAD

**Issue by WhiteRj** [tinohager/Nager.AmazonProductAdvertising#97]
Hello!
Are you planing to add support for UAE marketplace?

Best Regards

**Comment by tinohager** [comment]
Do you think UAE support is only add a new Endpoint?
https://github.com/tinohager/Nager.AmazonProductAdvertising/blob/master/Nager.AmazonProductAdvertising/AmazonEndpoint.cs

**Comment by WhiteRj** [comment]
Im not sure about this. i could not find any docs which could say are there any changes (compared with other EU)

**Comment by tinohager** [comment]
PAAPI5 have support for UAE https://github.com/tinohager/Nager.AmazonProductAdvertising/issues/99
