### ISSUE TITLE
New Similar Products not working Url.Route href

### ISSUE THREAD

**Issue by weberinfosp** [tinohager/Nager.AmazonProductAdvertising#98]
I tried to implement the new code of similar products only that utlizo Url.RouteUrl in my links, in the new version of lib axios (js)

New lib Axios:
`<div class="col-xs-6 col-md-6 col-lg-4 shoparticle text-center" v-for="item in data">
                                <div>
                                    <a :href="'/Amazon/Detail?articleNumber=' + item.Asin">
                                        <div class="overlay"><div class="text"><h4>Mehr Details</h4></small></div></div>
                                        <img :src="item.Image" :alt="item.Name" :title="item.Name" />
                                    </a>
                                </div>
                                {{item.Name | truncate(30, '...') }}
                            </div>`

Not Working Url.RouteUrl

my link:  `<a href=@Url.RouteUrl("DetalhesRoute", new { titulo = Util.UrlFriendly(product.Title), IdAsin = product.ASIN.ToLower() `})>`

`<div class="col-xs-6 col-md-6 col-lg-4 shoparticle text-center" v-for="item in data">
                                <div>
                                    **<a :href="'?????' + item.Asin">**
                                        <div class="overlay"><div class="text"><h4>Mehr Details</h4></small></div></div>
                                        <img :src="item.Image" :alt="item.Name" :title="item.Name" />
                                    </a>
                                </div>
                                {{item.Name | truncate(30, '...') }}
                            </div>`

 thanks

**Comment by tinohager** [comment]
Sorry but the website project is only for demo and not a part of the primary project.
